name: qtec_task
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

#-----------PACKAGES-------------------
dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.3.0
  cached_network_image: ^3.3.0
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  connectivity_plus: ^6.1.3
  google_fonts: ^6.2.1


# -------------- PACKAGES END ----------------

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


